version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "/docker/sirius-user-management"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "#patch"
    pull-request-branch-name:
      separator: "-"
