version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/sirius-user-management/Dockerfile
    ports: ["8888:8888"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://pact-stub:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  pact-stub:
    image: pactfoundation/pact-stub-server:v0.4.3
    ports: ["8080:8080"]
    command: ["-d", "pacts", "-p", "8080"]
    volumes:
      - type: volume
        source: pacts_data
        target: /app/pacts

  pa11y:
    build: ./pa11y-ci
    depends_on:
      - app
      - pact-stub
    environment:
      LHCI_BUILD_CONTEXT__CURRENT_HASH: $CIRCLE_SHA1

volumes:
  pacts_data:
    name: pacts_data
    external: true
